name: 'node-ssh-cmd'
description: 'ssh ec2 command'
inputs:
  private-key:
    description: 'aws private-key'
    required: true
    default: ''
  server-ip:
    description: 'aws ec2 server ip'
    required: true
    default: ''
  work-target:
    description: 'command label'
    required: true
    default: ''
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'index.js'