name: 'node-ssh-cmd'
description: 'ssh ec2 command'
inputs:
  private-key:
    description: 'aws private-key'
    required: true
    default: ''
  server-ip:
    description: 'aws ec2 server ip'
    required: true
    default: ''
  work-target:
    description: 'command label'
    required: true
    default: ''
  git-repo:
    description: 'git repo name'
    required: false
    default: ''
  repo-name:
    description: 'repo directory name'
    required: false
    default: ''
  image-name:
    description: 'docker image name'
    required: false
    default: 'express-img'
  container-name:
    description: 'docker container name'
    required: false
    default: ''
  container-port:
    description: 'docker container out port'
    required: false
    default: ''
  environment:
    description: 'docker run environment'
    required: false
    default: ''
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'index.js'